export const FETCH_SEARCH_RESULTS_REQUEST = 'FETCH_SEARCH_RESULTS_REQUEST';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_ERROR = 'FETCH_SEARCH_RESULTS_ERROR';

// export const FETCH_REPO_DETAIL_REQUEST = 'FETCH_REPO_DETAIL_REQUEST';
// export const FETCH_REPO_DETAIL_SUCCESS = 'FETCH_REPO_DETAIL_SUCCESS';
// export const FETCH_REPO_DETAIL_ERROR = 'FETCH_REPO_DETAIL_ERROR';

export const FETCH_README_REQUEST = 'FETCH_README_REQUEST';
export const FETCH_README_SUCCESS = 'FETCH_README_SUCCESS';
export const FETCH_README_ERROR = 'FETCH_REPO_DETAIL_ERROR';
